### ISSUE TITLE
Plugin injects a bunch of CSS to various parts of Moodle

### ISSUE THREAD

**Issue by ericmerrill** [justinhunt/moodle-atto_subtitle#1]
There are a bunch of CSS rules that seem like they should not be in here. Like:
`* {box-sizing: border-box;}`
Which is changing or breaking layout in various places. And why are so many rules being applied to the .file-upload, .tooltip, and .green-btn classes?

These rules need to be better constrained to do what is needed for the plugin only, because as it, this can cause a lot of unintended side effects.

**Comment by justinhunt** [comment]
Thanks Eric. Agreed. I will look into it

**Comment by justinhunt** [comment]
Sorry for the delay Eric. It should be better now
