### ISSUE TITLE
Global H1 style being added

### ISSUE THREAD

**Issue by rlorenzo** [justinhunt/moodle-atto_subtitle#2]
Found that when we installed this plugin that it was center aligning all h1 tags. It is because this style is added here:
https://github.com/justinhunt/moodle-atto_subtitle/blob/e2494b17d2b6ce9c0034e901dda57b0c469e3945/styles.css#L55

**Comment by justinhunt** [comment]
Thanks Rex. That should be fixed now. Appreciate it
https://github.com/justinhunt/moodle-atto_subtitle/commit/5cf6d0ee459240babfb380659752631f03552628
